apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260513-224619-r8zmo94t3nmu-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260513-224619-r8zmo94t3nmu.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260513-224619-r8zmo94t3nmu-service
            port:
              number: 80
