apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260513-224619-r8zmo94t3nmu-service
spec:
  selector:
    app: enterprise-system-20260513-224619-r8zmo94t3nmu
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
